### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Sission** [justagist/franka_ros_interface#17]
Hi! I tried to catkin build your package, however, it shows this error:

Errors     << franka_core_msgs:cmake /home/sission/ws_moveit/logs/franka_core_msgs/build.cmake.002.log                     
CMake Error at /home/sission/ws_moveit/build/franka_core_msgs/cmake/franka_core_msgs-genmsg.cmake:3 (message):
  Could not find messages which
  '/home/sission/ws_moveit/src/franka_ros_interface/franka_common/franka_core_msgs/msg/RobotState.msg'
  depends on.  Did you forget to specify generate_messages(DEPENDENCIES ...)?

  Cannot locate message [Errors] in package [franka_msgs] with paths
  [['/home/sission/ws_moveit/src/src/franka_ros/franka_msgs/msg',
  '/home/sission/ws_moveit/devel/.private/franka_msgs/share/franka_msgs/msg']]
Call Stack (most recent call first):
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:307 (include)
  CMakeLists.txt:34 (generate_messages)

**Comment by justagist** [comment]
Looks like catkin is not able to find the franka_msgs package. Please try rebuilding the package in a clean workspace. If that doesn't work, make sure you build franka_ros first (as mentioned in readme) and then build this package.

**Comment by Sission** [comment]
Thanks for your reply. However, it still does not work.
I create a new workspace by
$ mkdir workspace
in the root.
then 
$ mkdir src

Also, I checked libfranka and franka-ros installation:
sission@Ros:~/workspace/src$ sudo apt install ros-melodic-franka-ros
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-melodic-franka-ros is already the newest version (0.6.0-1bionic.20200930.133157).

sission@Ros:~/workspace/src$ sudo apt install ros-melodic-libfranka
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-melodic-libfranka is already the newest version (0.8.0-1bionic.20200801.024519).

However, the same error still happened. Did I miss something?

**Comment by justagist** [comment]
Start a new terminal session without sourcing the "ws_moveit" workspace. Your session seems to have sourced both workspaces which is messing things up because there is another build of franka_ros exists in "ws_moveit".
This is not really an issue you should raise for this package. This looks like your ros path is messed up. You have a build of franka_msgs package in your "ws_moveit" workspace, which seems to be in the ros path, and is now overshadowing the global installation of franka_ros's franka_msgs package. 
Either remove the existing build of franka_msgs from your "ws_moveit" or remove that workspace from your path. Simplest way to remove would be to remove all franka_ros and franka_ros_interface packages from the src folder of "ws_moveit" and also delete the folders "ws_moveit/devel" and "ws_moveit/build".

**Comment by Sission** [comment]
It works! Thanks!
